config/routes.rb
Rails.application.routes.draw do
  get 'policies/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "policy/:policy_type", to: "policies#show"
  post 'subscribe', to: 'subscribers#create'
  post 'send_email', to: 'subscribers#send_email'
  get '/unsubscribe/:id', to: 'subscribers#destroy', as: 'unsubscribe'
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/newsletter_template.rb
class NewsletterTemplate < ApplicationRecord
end

app/models/policy.rb
class Policy < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "id_value", "policy_type", "title", "updated_at"]
      end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  def show
    @policy = Policy.find_by(policy_type: params[:policy_type])
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

    def create
        @user = Subscriber.new(email: params[:email])
        if @user.save
            NewsletterMailer.welcome_subscriber(@user).deliver_now
            flash[:success] = "Subscribed Successfully"
        else
            flash[:error] = "Something went wrong please try again later"
        end
    end

    def destroy
        @user = Subscriber.find(params[:id])
        if @user.delete
            NewsletterMailer.unsubscribe(@user).deliver_now
            flash[:success] = "Unsubscribed Successfully"
        else
            flash[:error] = "Something went wrong please try again later"
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kinghills2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="@fortawesome/fontawesome-free/css/all.css">
    
    <style>
    .gray{
      background-color: rgb(248, 247, 247);
    }
    </style>
  </head>

  <body>
    <main class="gray">
    <%= render "shared/navbar" %>
      <%= yield %>
      <%= render "shared/subscribe" %>
    <%= render "shared/download_app" %>
    </main>
  </body>
</html>

app/views/policies/_poster.html.erb
<style>
    .policy_background_poster{
        background-image: url(<%= asset_path('policy_background.jpg') %>);
        height: 300px;
        background-size: cover;
        text-align: center;
        margin-bottom: 50px;
    }

    .policy_background_poster h1{
        width: 100%;
        font-weight:700 ;
        color: orangered;
        padding-top: 90px;
    }

    .policy_background_poster p{
        text-align: left;
        font-size: 16px;
        font-weight: 700;
        width: 50%;
        margin: auto;
        color: white;
    }
</style>


<div class="policy_background_poster">
    <h1>
    <%= @policy.title.upcase %>
    </h1>

    <p>
        Best Offer Travel Packages Deals made especially for you, Everything you need—on a budget. Thank You From kinghillstravels
    </p>
</div>

app/views/policies/show.html.erb
<%= render "poster" %>
<div class="main_container" >
  <div class="title_container">
      <p class="title ">
        <%= @policy.title %>
      </p>
  </div>
  <div class="description">
    <%= @policy.description.html_safe %>
  </div>
</div>

app/views/shared/_download_app.html.erb
<style>
    .app_background{
        background-color: white;
        height: 300px;
        text-align: center;
        margin-bottom: 50px;
    }

    .app_download{
        width: 100%;
        font-weight:700 ;
        line-height: 15px;
    }

    .app_mobile_orange{
        color: orangered;
    }

    .app_background p{
        text-align: left;
        font-size: 15px;
        font-weight: 300;
        width: 32%;
        margin: auto;
        margin-bottom: 30px;
    }

    .download_padding_top{
        padding-top: 80px ;
        }

        .download_button{
            margin: 25px;
            background-color: orangered;
            font-size: 14px;
            
            padding: 8px 15px;
            border-radius: 7px;
            }
</style>


<div class="app_background">
    <h2 class="app_download download_padding_top">
        Download
    </h2>

    <h1 class="app_download app_mobile_orange">
        Mobile App
    </h1>

    <p class="">
        Download Kinghills Travels App to Book Your Trip With Exciting Offers.
    </p>

    <%= link_to "Google Play", "https://play.google.com/store/apps", class: "download_button", style: "color: white; text-decoration: none;" %>
</div>

app/views/shared/_navbar.html.erb
<style>
    .navbar_outer_container{
        width: 100%;
    }

    .navbar_inner_container{
        width: 80%;
        margin: 0 auto;
        /* display: flex; */
        /* justify-content: space-around; */
        padding: 2%;
    }

    .navbar_list_ul{
        display: flex;
        justify-items: end;
        gap: 2%;
        align-items: center;
        list-style-type: none;
        /* margin-right: 30px; */
        font-size: 14px;
    }

    .logo{
        width: 10%;
    }

    .navbar_right{
        margin-top: 20px;
            display: flex;
        justify-content: space-around;
        align-items: center;
    }

    .navbar_profile_ul{
        display: flex;
        gap: 1%;
        align-items: center;
        list-style-type: none;
    }

    .navbar_profile_ul li{
       /* padding: 5px; */
    }

    .navbar_profile_ul li a{
        text-decoration: none;
        cursor: pointer;
        border: 1px solid black;
        padding: 6px 9px;
        border-radius: 50%;
    }

    .navbar_profile_ul li a:hover{
        color: orangered;
        cursor: pointer;
    }

    .navbar_list_ul li a:hover{
        color: orangered;
        cursor: pointer;
    }

    .navbar_list_ul li a{
        text-decoration: none;
        cursor: pointer;
    }

    .navbar_kh_button a{
        background-color: orangered;
        color: white;
        padding: 6px 8px;
        border-radius: 5%;
    }

    .navbar_kh_button:hover{
        background-color: rgb(182, 49, 0);
        color: white;
    }

    .navbar_kh_button a:hover{
        color: white;
    }

    .navbar_upper_section select{
        -webkit-appearance: none; /* Remove default arrow for WebKit browsers */
        -moz-appearance: none; /* Remove default arrow for Firefox */
        appearance: none; /* Remove default arrow for other browsers */
        background-image: none; /* Remove default arrow background */
    }

    .navbar_upper_section{
        display: flex;
        /* border: 1px solid black; */
        /* width: auto; */
    }

    .navbar_search_section{
        border-radius: 30px;
        width: 70%;
        
        display: flex;
        align-items: center;
        border: 2px solid black;
    }

    .navbar_search_section_button{
        border: 2px solid black;
        padding: 15px 20px;
    }

    .navbar_search_section select{
        font-size: 16px;
        width: 250px;
        /* padding: 1%; */
        text-align: center;
        padding: 15px 0;
    }

    .navbar_left_search_section{
        border-left: 1px solid black;
    }

    .navbar_first_search_select{
        border-radius: 30px 0px 0px 30px;
    }

    .select_border_none{
        border: none;
    }

    .navbar_list_container{
        width: 70%;
    }

</style>

<div class="navbar_outer_container">
    <div class="navbar_inner_container">
        <div>
            <div class="navbar_upper_section">
                <div class=" navbar_search_section">
                    <div>
                        <select name="" id="" class="select_border_none navbar_first_search_select">
                            <option>Where do you want to travel?</option>
                            <option value="">Andaman and Nicobar</option>
                        </select>
                    </div><div class="navbar_left_search_section">
                        <select name="" id="" class="select_border_none ">
                            <option>Budget</option>
                            <option value="">Above 35000</option>
                        </select>
                    </div><div class="navbar_left_search_section">
                        <select name="" id="" class="select_border_none ">
                            <option>Group Tour</option>
                            <option value="">Standard Tour</option>
                        </select>
                    </div>
                    <button class="navbar_search_section_button"> S </button>
                </div>
                <div>
                    <ul class="navbar_profile_ul">
                        <li>
                            <a href="">C</a>
                        </li>
                        <li>
                            <a href="">P</a>
                        </li>
                        <li>
                            <a href="">B</a>
                        </li>
                    </ul>
                </div>
                
        </div>
       
        <div class="navbar_right">
            <div class="logo">
                <%= image_tag 'logo.png', alt: 'logo', class: 'img-fluid', style: 'width: 100px;' %>
            </div>
            <div class="navbar_list_container">
                <ul class="navbar_list_ul">
                    <li>
                        <a href="/policy/cancellation-policy">Home</a>
                    </li>
                    <li>
                        <a href="">Group Tours</a>
                        </li>
                    <li>
                        <a href="">Personal Tours</a>
                        </li>
                    <li>
                        <a href="">Customised Tours</a>
                        </li>
                    <li>
                        <a href="">Awards & certificates</a>
                    </li>
                    <li>
                        <a href="">Our Branches</a>
                    </li>
                    <li class="navbar_kh_button">
                        <a href="">+ KH Partners</a>
                            
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/shared/_subscribe.html.erb
<style>
    .app_background{
        background-color: orangered;
        height: 300px;
        text-align: center;
        margin-bottom: 50px;
    }

    .app_download{
        width: 100%;
        font-weight:700 ;
        line-height: 15px;
    }

    .app_mobile_orange{
        color: orangered;
    }

    .app_background p{
        text-align: left;
        font-size: 15px;
        font-weight: 300;
        width: 32%;
        margin: auto;
        margin-bottom: 30px;
    }

    .download_padding_top{
        padding-top: 80px ;
        }

        .download_button{
            margin: 25px;
            background-color: orangered;
            font-size: 14px;
            
            padding: 8px 15px;
            border-radius: 7px;
            }
</style>


<div class="app_background">
    <h2 class="app_download download_padding_top">
        Subscribe
    </h2>

    <h1 class="app_download app_mobile_orange">
        Our Newletter
    </h1>

    <p class="">
        It is a long established fact that a reader will be distracted by the readable.
    </p>

    <form action="<%= subscribe_path %>" method="post">
        <input type="email" id="email" name="email" placeholder="Enter Email" required>
        <button type="submit">Subscribe</button>
  </form>
</div>

app/views/subscribers/destroy.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Unsubscribe</title>
</head>
<body>
  <h1>Unsubscribe from Our Newsletter</h1>
  <% if flash[:success] %>
    <h1 class="success"><%= flash[:success] %></h1>
  <% elsif flash[:error] %>
    <h1 class="error"><%= flash[:error] %></h1>
  <% end %>
</body>
</html>